### ISSUE TITLE
no novisad link  in main menu on https://s95.ru/

### ISSUE THREAD

**Issue by xrinat** [vol1ura/Sat_9am_5km#123]
Отсутствие в списке мероприятий "Нови Сад".
При переносе информации о забегах в Нови Саде в отдельное мероприятие  https://s95.ru/events/novisad не поправили в главном меню. 
Коллекция @country_events содержит последним событием только "S95 & Friends" (последняя  которое датировано [03.06.2023](https://s95.ru/activities/483)). А прямой ссылки на https://s95.ru/events/novisad нет. Можно зайти только если знаешь ссылку или в рассылке ботом

  def find_country_events
    @country_events = Country.find_by(code: top_level_domain).events
  end

**Comment by vol1ura** [comment]
Привет, @xrinat 
Сейчас  есть деление мероприятий по домену, т.е. на `s95.ru` отображаются только российские забеги, на `s95.rs` - только сербские. Информация о региональных сайтах сейчас содержится только на страничке `https://s95.ru/pages/about`, а информация о забегах в Нови Саде есть в меню и на главной [s95.rs](https://s95.rs). 

Вот бота, думаю, стоит поправить, чтобы он делал ссылку на правильный домен в зависимости от страны мероприятия.

Есть планы переверстать главную страничку и сделать там подменю с выбором страны. Пока не доходят руки до этого.

**Comment by vol1ura** [comment]
[Поправил ссылки](https://github.com/vol1ura/Sat_9am_5km/commit/de446f9f4312abd1c8b47381961d79e75dc18d27) в рассылках бота, теперь должна учитываться страна забега или выбранные домашний забег участника. Ссылка будет на соответствующий сайт.

**Comment by vol1ura** [comment]
Тут закрываю, ссылка на Novisad есть на сербском домене [s95.rs](https://s95.rs)
