### ISSUE TITLE
Minor issues in s95.rs

### ISSUE THREAD

**Issue by radulle** [vol1ura/Sat_9am_5km#165]
Thank you for your effort, would help but don't have enough experience with Ruby (can help with JS if there's a need). I noticed a few issues you might want to address:
1. Is it possible for the system to support event names that consist of two or more words? I know it's nitpicking, but Novi Sad is two words.
2. Password reset leads to s95.ru even when initiated from s95.rs.
3. Most email clients (e.g. gmail) will throw password reset emails to trash since server is untrusted. Since you are already using Telegram as means of registering users maybe:
    * it'd be better to use bot to reset passwords
    * even better use [Telegram's Login Widget](https://core.telegram.org/widgets/login)

**Comment by vol1ura** [comment]
Nikola, hello. Thank you for your help and valuable notices.

1. Yes, of course. I've changed the even name. I also can change name in url like `novi_sad`, but old links will be invalid then. What you think about it?
2. Will try to fix. I see there is no translations in email partials.
3. Yes, it's a good idea. I've already thought about making a login to the site using a link that can be obtained through the bot, but I don't have enough time to implement it yet, but I'll try anyway. Implementing password reset via a bot is also a good idea. With telegram login widget I have some troubles with code to check a hash.

**Comment by nradulaski-godaddy** [comment]
Sorry for late response:
1. I believe leaving url as it was is ok.
2. New emails look good, there are some minor wording issues, I'll create a small PR.
3. I believe that with Telegram login you can do away with user/password type of login as all have to have Telegram anyways to register and that's their ID. This should be security improvement too.
